version: '2.1'
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - checkout
      - run:
          name: "Build mit Maven"
          command: mvn $MAVEN_CLI_OPTS \
            -Dvaadin.offlineKey="…" \
            clean package \
            -Pproduction -e
      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    steps:
      - checkout
      - run:
          name: "Maven Tests"
          command: mvn test -e
      - store_artifacts:
          path: reports
          destination: reports

  build-docker-image:
    docker:
      - image: cimg/azure:2025.01
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build und Push Docker Image"
          command: |
            docker buildx build . -t byteme.azurecr.io/byteme:latest .
            echo $DOCKER_PASS \
              | docker login byteme.azurecr.io \
                -u $DOCKER_USER --password-stdin
            docker push vaadincrm.azurecr.io/byteme:latest

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image
